Samana/ViewModels/LidViewModel.cs
using DataSource.Enums;
using DataSource.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Samana.ViewModels
{
    public class LidViewModel
    {
        public LidViewModel()
        {
            NoodPersonen = new List<NoodPersoon>();
        }

        //TODO: Id's van lidsoort etc toevoegen...
        public int Id { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public int LidsoortId { get; set; }
        public string Lidsoort { get; set; }
        public Geslacht Geslacht { get; set; }
        [DataType(DataType.Date, ErrorMessage = "Datum is fout.")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required(ErrorMessage = "Geboortedatum is verplicht.")]
        [Range(typeof(DateTime), "1/1/1850", "1/1/2017", ErrorMessage = "datum ligt te ver in het verleden...")]
        public DateTime GeboorteDatum { get; set; }
        public string Adres { get; set; }
        public string HuisNr { get; set; }
        public int Postcode { get; set; }
        public string Gemeente { get; set; }
        public string RijksregisterNr { get; set; }
        public string Tel { get; set; }
        public string GSM { get; set; }
        public string Email { get; set; }
        public bool Rolstoel { get; set; }
        public bool Rusthuis { get; set; }
        public bool ThuisGebonden { get; set; }
        public bool Rollator { get; set; }
        public bool GaandeZieke { get; set; }
        public bool LiggendeZieke { get; set; }
        public List<NoodPersoon> NoodPersonen { get; set; }
        public List<Verantwoordelijkheid> Verantwoordelijkheden { get; set; }
        public List<Lid> Beschermelingen { get; set; }
        public string Mentor { get; set; }
        public int? MentorId { get; set; }
        public string Opmerking { get; set; }
        public List<Verantwoordelijkheid> AlleVerantwoordelijkheden { get; set; }
        public string Leeftijd { get; set; }
        public bool IsSelected { get; set; }

        public List<NoodPersoon> GetNoodPersonen()
        {
            List<NoodPersoon> persList = new List<NoodPersoon>();
            
            return persList;
        }
    }
}

Samana/Controllers/LedenController.cs
using DataSource.Model;
using Samana.Services;
using Samana.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;
using System;
using System.Linq;
using ClosedXML.Excel;
using System.Data;
using System.IO;
using DataSource;
using System.Net;
using Samana.Models;

namespace Samana.Controllers
{
    public class LedenController : Controller
    {
        private LedenViewModel _ledenViewModel = new LedenViewModel();
        private LidService _lidService = new LidService();
        private NoodPersoonService _noodPersoonService = new NoodPersoonService();
        private ExportToExcelService _exportToExcelService = new ExportToExcelService();
        private int limit = 5;
        private Models.SearchOption _searchOption = new Models.SearchOption();
        // GET: Leden
        public ActionResult Index(int? id)
        {
            GeneralSetup();            
            if (Request.IsAjaxRequest())
            {
                _searchOption = SetSearchOption();               
                _searchOption.PageId = id ?? 0;
                _ledenViewModel.Leden = SetLeden(_searchOption);                
                return PartialView("~/Views/Partials/LedenData.cshtml",_ledenViewModel);
            }
            else
            {
                Session["searchoption"] = null;
                _searchOption = SetSearchOption();
                SetInfo(_lidService.LedenToViewModelList(_lidService.GetAlleLeden()));
            }

            return View(_ledenViewModel);
        }
        public Models.SearchOption SetSearchOption()
        {
            if(Session["searchoption"] == null)
            {
                _searchOption.Option = SearchOptionEnum.AlleLeden.ToString();
                Session["searchoption"] = _searchOption;
            }

            return Session["searchoption"] as Models.SearchOption;
        }
        

        [HttpPost]
        public ActionResult Index(int? id, int? soortId, string tekst, string tekstParam, string sortParam)
        {
            _searchOption.PageId = id;

            //zoeken op lidsoort
            if (soortId != null)
            {
                if (soortId == 0)
                {
                    _searchOption.Option = SearchOptionEnum.AlleLeden.ToString();
                }
                else
                {
                    _searchOption.Option = SearchOptionEnum.Lidsoort.ToString();
                    _searchOption.IntValue = soortId;
                }
            }

            //zoeken op naam
            else if (tekst != null && tekstParam != null)
            {
                if (tekstParam == "Voornaam") {
                    _searchOption.Option = SearchOptionEnum.Voornaam.ToString();
                }
                if(tekstParam == "Achternaam")
                {
                    _searchOption.Option = SearchOptionEnum.Achternaam.ToString();
                }
                _searchOption.StringValue1 = tekst;
            }
            else
            {
                _searchOption.Option = SearchOptionEnum.AlleLeden.ToString();
            }



            foreach (var pers in _noodPersoonService.GetAlleNoodPersonen())
            {
                LidViewModel lid = _ledenViewModel.Leden.Find(m => m.Id == pers.LidId);
                if (lid != null)
                {
                    lid.NoodPersonen.Add(pers);
                }
            }           

            Session["searchoption"] = _searchOption;
            
            _ledenViewModel.Leden = SetLeden(_searchOption);
            return View(_ledenViewModel);
        }

        public List<LidViewModel> SetLeden(Models.SearchOption searchOption)
        {
            int page = Convert.ToInt16(searchOption.PageId) * limit;
            List<LidViewModel> ledenlist = new List<LidViewModel>();
            switch ((SearchOptionEnum)Enum.Parse(typeof(SearchOptionEnum), searchOption.Option))
            {
                case SearchOptionEnum.AlleLeden:
                    _ledenViewModel.Leden = _lidService.LedenToViewModelList(_lidService.GetAlleLedenByStep(limit, page));
                    ledenlist = _lidService.LedenToViewModelList(_lidService.GetAlleLeden());
                    SetInfo(ledenlist);
                    break;
                case SearchOptionEnum.Lidsoort:
                    _ledenViewModel.Leden = _lidService.LedenToViewModelList(_lidService.GetLedenPerSoortByStep(_searchOption.IntValue, limit, page));
                    ledenlist = _lidService.LedenToViewModelList(_lidService.GetLedenPerSoort(_searchOption.IntValue));
                    SetInfo(ledenlist);
                    break;
                case SearchOptionEnum.Voornaam:
                    _ledenViewModel.Leden = _lidService.LedenToViewModelList(_lidService.GetLedenOpVoorNaamByStep(_searchOption.StringValue1, limit, page));
                    ledenlist = _lidService.LedenToViewModelList(_lidService.GetLedenOpVoorNaam(_searchOption.StringValue1));
                    SetInfo(ledenlist);
                    break;
                case SearchOptionEnum.Achternaam:
                    _ledenViewModel.Leden = _lidService.LedenToViewModelList(_lidService.GetLedenOpAchterNaamByStep(_searchOption.StringValue1, limit, page));
                    ledenlist = _lidService.LedenToViewModelList(_lidService.GetLedenOpAchterNaam(_searchOption.StringValue1));
                    SetInfo(ledenlist);
                    break;
            }
            return _ledenViewModel.Leden;
        }

        public void GeneralSetup()
        {
            foreach (var pers in _noodPersoonService.GetAlleNoodPersonen())
            {
                if(_ledenViewModel.Leden.Find(m=>m.Id == pers.LidId) != null){
                    _ledenViewModel.Leden.Find(m => m.Id == pers.LidId).NoodPersonen.Add(pers);
                }               
            }
        }

        public void SetInfo(List<LidViewModel> ledenlist)
        {

            LidViewModel oudstelid = _lidService.GetOudsteLid(ledenlist);
            TempData["oudstelid"] = oudstelid.Voornaam + " " + oudstelid.Achternaam + " (" + oudstelid.Leeftijd + " jaar)";

            LidViewModel jongstelid = _lidService.GetjongsteLid(ledenlist);
            TempData["jongstelid"] = jongstelid.Voornaam + " " + jongstelid.Achternaam + " (" + jongstelid.Leeftijd + " jaar)";

            TempData["aantalLeden"] = ledenlist.Count();
            TempData["aantalkernleden"] = ledenlist.Count(m => m.LidsoortId == 1);
            TempData["aantalmedewerkers"] = ledenlist.Count(m => m.LidsoortId == 2);
            TempData["aantalgewoneleden"] = ledenlist.Count(m => m.LidsoortId == 3);
            TempData["aantalmannen"] = ledenlist.Count(m => m.Geslacht == DataSource.Enums.Geslacht.man);
            TempData["aantalvrouwen"] = ledenlist.Count(m => m.Geslacht == DataSource.Enums.Geslacht.vrouw);

        }


        public ActionResult Create()
        {
            _ledenViewModel.Leden = new List<LidViewModel>();
            _ledenViewModel.Leden.Add(new LidViewModel());
            return View(_ledenViewModel);
        }

        [HttpPost]
        public ActionResult Create(LidViewModel lidViewModel)
        {
            _ledenViewModel.Leden = new List<LidViewModel>();
            _ledenViewModel.Leden.Add(lidViewModel);
            if (ModelState.IsValid)
            {
                _lidService.SaveNewLidViewModelToDb(lidViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(_ledenViewModel);
            }
        }
        public ActionResult Edit(int? id)
        {
            LidViewModel lidviewModel = _lidService.LidToLidViewModel(_lidService.GetAlleLeden().Find(m => m.Id == id));
            _ledenViewModel.Leden = new List<LidViewModel>();
            _ledenViewModel.Leden.Add(lidviewModel);
            return View(_ledenViewModel);
        }


        [HttpPost]
        public ActionResult Edit(LidViewModel lidViewModel)
        {
            _ledenViewModel.Leden = new List<LidViewModel>();
            _ledenViewModel.Leden.Add(lidViewModel);
            if (ModelState.IsValid)
            {
                _lidService.SaveLidViewModelToDb(lidViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(_ledenViewModel);
            }
        }

        public ActionResult Delete(int? id)
        {
            LidViewModel lidViewModel = _lidService.LidToLidViewModel(_lidService.GetAlleLeden().Find(m => m.Id == id));
            return View(lidViewModel);
        }

        [HttpPost]
        public ActionResult Delete(LidViewModel lidViewModel)
        {
            _lidService.deleteLidViewModelFromDb(lidViewModel.Id);
            return RedirectToAction("Index");
        }

        public ActionResult AddNoodPersoon(int? id)
        {
            LidViewModel lidViewModel = _lidService.LidToLidViewModel(_lidService.GetAlleLeden().Find(m => m.Id == id));
            NoodPersoon noodpersoon = new NoodPersoon();
            noodpersoon.Id = _noodPersoonService.GetMaxId() + 1;
            noodpersoon.LidId = lidViewModel.Id;
            Session["Lid"] = lidViewModel;
            return View(noodpersoon);
        }


        [HttpPost]
        public ActionResult AddNoodPersoon(NoodPersoon pers)
        {

            if (ModelState.IsValid)
            {
                pers.LidId = (Session["Lid"] as LidViewModel).Id;
                _noodPersoonService.SaveNoodPersoon(pers);
                return RedirectToAction("Index");
            }
            else
            {
                return View(pers);
            }
        }

        [HttpPost]
        public ActionResult RemoveNoodPersoon(int? id)
        {
            _noodPersoonService.RemoveNoodPersoon(id);
            GeneralSetup();
            return View(_ledenViewModel);
        }

Samana/Views/Partials/LedenData.cshtml
@model Samana.ViewModels.LedenViewModel

@foreach(var lid in Model.Leden)
{
    <div class="lid-general">
        <div class="lid-info">
            <div class="lid-info-name">

                @switch (lid.Geslacht)
                {
                    case DataSource.Enums.Geslacht.man:
                        <img src="~/Img/Icons/male_user_icon_64.png" />
                        break;
                    case DataSource.Enums.Geslacht.vrouw:
                        <img src="~/Img/Icons/female_user_icon_64.png" />
                        break;
                    default:
                        <img src="~/Img/Icons/male_user_icon_64.png">
                        break;
                }

            </div>
                <div class="lid-info-buttons">
                    <ul>
                        <li>
                            <button type="button" class="user-btn-transparant" onclick="location.href='@Url.Action("Edit", "Leden", new { id = lid.Id })'" title="Lid Bewerken"><img src="~/Img/Icons/Wrench16.png" /></button>
                        </li>
                        <li>
                            <button type="button" class="user-btn-transparant" onclick="location.href='@Url.Action("Delete", "Leden", new { id = lid.Id })'" title="Lid Verwijderen"><img src="~/Img/Icons/Trash16.png" /></button>
                        </li>
                        <li>
                            @if (lid.LidsoortId == 1)
                            {
                                <button type="button" class="user-btn-transparant" onclick="location.href='@Url.Action("MentorToExcel", "Leden", new { id = lid.Id })'" title="Beschermelingen afdrukken"><img src="~/Img/Icons/Excel16.png" /></button>
                            }
                        </li>
                    </ul>
                </div>

            
            <div style="clear:both;">@lid.Voornaam @lid.Achternaam (@lid.Lidsoort)</div>
        </div>
        <div class="lid-noodpersonen">
            @if (lid.NoodPersonen != null)
            {
                <b>Noodpersonen</b>
                        <ul>
                            @foreach (var pers in lid.NoodPersonen)
                            {
                                <li><i>@pers.Voornaam @pers.Achternaam (@pers.Relatie):@pers.Nummer<button onclick="RemovePerson(@pers.Id)" title="Verwijder deze persoon" class="user-btn-transparant"><img src="~/Img/Icons/Trash16.png" /></button></i></li>
                            }
                            <li><button onclick="location.href='@Url.Action( "AddNoodPersoon", "Leden", new { id = @lid.Id })'" title="Voeg een noodpersoon toe" class="user-btn-noodpersoon">Noodpersoon toevoegen<img src="~/Img/Icons/Add16.png" /></button></li>
                        </ul>
            }
        </div>
        <div class="lid-beschermelingen">
            @if (lid.MentorId != null || lid.MentorId > 0)
            {
                <b>Mentor</b>
                <p><i>@lid.Mentor</i></p>
            }
            @if ((lid.MentorId == null || lid.MentorId == 0) && (lid.LidsoortId == 2 || lid.LidsoortId == 3))
            {

                <p><i> @Html.ActionLink("Kies een mentor", "SelectMentor", "Leden", new { id = @lid.Id }, null)</i></p>

            }

            @if (lid.LidsoortId == 1)
            {
                <b>Beschermelingen (@lid.Beschermelingen.Count)</b>
                <ul>
                    @foreach (var besch in lid.Beschermelingen)
                    {
                        <li><i>@besch.Voornaam @besch.Achternaam,</i></li>
                    }
                </ul>
            }
        </div>

        <div class="lid-footer"></div>

    </div>


}

Samana/Views/Partials/LidForm.cshtml
@model Samana.ViewModels.LedenViewModel
<script>
    $(document).ready(function () {
        setMentorListbox();
    });
    function setDropDown() {
        setMentorListbox();
    }
</script>
<ul>
    <li>
        <label for="Voornaam">Voornaam</label>
        <input type="text" name="Voornaam" maxlength="100" placeholder="Vul hier je Voornaam in." value="@Model.Leden.First().Voornaam" />
        @Html.ValidationMessageFor(m => m.Leden.First().Voornaam, "")
    </li>
    <li>
        <label for="Achternaam">Achternaam</label>
        <input type="text" name="Achternaam" maxlength="100" placeholder="Vul hier je Achternaam in." value="@Model.Leden.First().Achternaam" />
        @Html.ValidationMessageFor(m => m.Leden.First().Achternaam, "")
    </li>
    <li>
        <label for="LidSoortId">Lidsoort</label>
        @Html.DropDownListFor(m => m.Leden.First().LidsoortId, new SelectList(Model.LidsoortenSelectList, "Value", "Text", Model.Leden.First().LidsoortId), htmlAttributes: new { @onchange = "setDropDown()" })
        @Html.ValidationMessageFor(m => m.Leden.First().LidsoortId, "")
    </li>
    <li>
        <label for="MentorId">Mentoren</label>
        @Html.DropDownListFor(m => m.Leden.First().MentorId, new SelectList(Model.MentorenSelectList, "Value", "Text", Model.Leden.First().MentorId), new { @id = "mentorId" })
        @Html.ValidationMessageFor(m => m.Leden.First().MentorId, "")
    </li>
    <li>
        <label for="Geslacht">Geslacht</label>
        @Html.EnumDropDownListFor(m => m.Leden.First().Geslacht)
        @Html.ValidationMessageFor(m => m.Leden.First().Geslacht, "")
    </li>
    <li>
        <label for="GeboorteDatum">Geboortedatum</label>
        @Html.EditorFor(m => m.Leden.First().GeboorteDatum)
        @Html.ValidationMessageFor(m => m.Leden.First().GeboorteDatum, "")
    </li>
    <li>
        <label for="Adres">Adres</label>
        <input type="text" name="Adres" maxlength="100" placeholder="Vul hier je adres in." value="@Model.Leden.First().Adres" />

        @Html.ValidationMessageFor(m => m.Leden.First().Adres, "")
    </li>
    <li>
        <label for="HuisNr">Huisnr</label>
        <input type="number" name="HuisNr" maxlength="100" placeholder="Hier komt je huisnr." value="@Model.Leden.First().HuisNr" />
        @Html.ValidationMessageFor(m => m.Leden.First().HuisNr, "")
    </li>
    <li>
        <label for="Postcode">Postcode</label>
        @Html.DropDownListFor(m => m.Leden.First().Postcode, new SelectList(Model.GemeenteSelectList, "Value", "Text", Model.Leden.First().Postcode))
        @Html.ValidationMessageFor(m => m.Leden.First().Postcode, "")
    </li>
    <li>
        <label for="RijksregisterNr">RijksregisterNr</label>
        <input type="text" name="RijksregisterNr" maxlength="100" placeholder="Je rijksregisternr." value="@Model.Leden.First().RijksregisterNr" />
        @Html.ValidationMessageFor(m => m.Leden.First().RijksregisterNr, "")
    </li>
    <li>
        <label for="Tel">Tel</label>
        <input type="text" name="Tel" maxlength="100" placeholder="Telefoonnummer." value="@Model.Leden.First().Tel" />
        @Html.ValidationMessageFor(m => m.Leden.First().Tel, "")
    </li>
    <li>
        <label for="GSM">GSM</label>
        <input type="text" name="GSM" maxlength="100" placeholder="GSM-nummer" value="@Model.Leden.First().GSM" />
        @Html.ValidationMessageFor(m => m.Leden.First().GSM, "")
    </li>
    <li>
        <label for="Email">E-mail</label>
        <input type="email" name="Email" maxlength="100" placeholder="E-mail adres" value="@Model.Leden.First().Email" />
        @Html.ValidationMessageFor(m => m.Leden.First().Email, "")
    </li>
    <li>
        <label for="Rolstoel">Rolstoel gebruiker</label>
        @Html.EditorFor(m => m.Leden.First().Rolstoel)
        @Html.ValidationMessageFor(m => m.Leden.First().Rolstoel, "")
    </li>
    <li>
        <label for="Rusthuis">Rolstoel gebruiker</label>
        @Html.EditorFor(m => m.Leden.First().Rusthuis)
        @Html.ValidationMessageFor(m => m.Leden.First().Rusthuis, "")
    </li>
    <li>
        <label for="ThuisGebonden">Thuisgebonden</label>
        @Html.EditorFor(m => m.Leden.First().ThuisGebonden)
        @Html.ValidationMessageFor(m => m.Leden.First().ThuisGebonden, "")
    </li>
    <li>
        <label for="Rollator">Rollator</label>
        @Html.EditorFor(m=>m.Leden.First().Rollator)
        @Html.ValidationMessageFor(m=>m.Leden.First().Rollator,"")
    </li>
    <li>
        <label for="LiggendeZieke">Liggende zieke</label>
        @Html.EditorFor(m => m.Leden.First().LiggendeZieke)
        @Html.ValidationMessageFor(m => m.Leden.First().LiggendeZieke, "")
    </li>
    <li>
        <label for="GaandeZieke">Gaande zieke</label>
        @Html.EditorFor(m => m.Leden.First().GaandeZieke)
        @Html.ValidationMessageFor(m => m.Leden.First().GaandeZieke, "")
    </li>
    <li>
        <label for="Opmerking">Opmerking</label>
        <textarea name="Opmerking" onkeyup="adjust_textarea(this)"></textarea>
        @Html.ValidationMessageFor(m => m.Leden.First().Opmerking, "")
    </li>

    <li>
        <input type="submit" value="Bewaar" />
    </li>
</ul>